# Generated by Django 5.2.17 on 2026-09-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcreader',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='nfcreader',
            index=models.Index(fields=['device', 'created_at'], name='idx_nfcreader_dev_time'),
        ),
    ]
